#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  6 09:58:57 2017

@author: ethels
"""
import pandas as pd
movies = pd.read_csv('http://bit.ly/imdbratings')
print(movies.head())
Above_200 = movies[movies.duration >= 200]
print(Above_200.head())