#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 12 10:07:04 2017

@author: ethels
"""
from matplotlib import pyplot
from pandas import Series
from pandas import datetime
from pandas import read_csv
series = read_csv('shear4.csv', header=0)#,parse_dates=[0], index_col=0, squeeze=True)
#upsample = series.resample('H').mean()
#interpolated = upsample.interpolate(method='spline', order=2)
print(series.describe())
series.plot()
pyplot.show()

#series = read_csv('shampoo-sales.csv', header=0, parse_dates=[0], index_col=0,
#               squeeze=True, date_parser=parser)
#upsampled = series.resample('D').mean()
#interpolated = upsampled.interpolate(method='spline', order=2)
#print(interpolated.head(32))
#interpolated.plot()
#pyplot.show()
#print(series.head(4))
